default_install_hook_types:
# Mandatory to install both pre-commit and pre-push hooks (see https://pre-commit.com/#top_level-default_install_hook_types)
# Add new hook types here to ensure automatic installation when running `pre-commit install`
- pre-commit
- pre-push
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-json
  - id: check-added-large-files

- repo: local
  hooks:
  - id: ruff-format
    name: Formatting (ruff)
    entry: ruff format
    language: system
    types: [python]
    stages: [commit]
  - id: ruff-check
    name: Linting (ruff)
    entry: ruff check
    language: system
    types: [python]
    stages: [commit]
  - id: mypy
    name: Type checking (mypy)
    entry: make mypy
    pass_filenames: false
    language: system
    types: [python]
    stages: [commit]
  - id: test
    name: Unit testing (pytest)
    entry: make test
    pass_filenames: false
    language: system
    types: [python]
    stages: [push]
<% if (includeApi && apiInfrastructure !== null) { -%>
  - id: terraform-docs
    name: Update terraform docs
    entry: cd terraform && make docs
    language: system
    stages: [ commit ]
  - id: terraform-fmt
    name: Format terraform code
    entry: cd terraform && make fmt
    language: system
    stages: [ commit ]
  - id: terraform-lint
    name: Validates all Terraform configuration files with TFlint
    entry: cd terraform && make lint
    language: system
    stages: [ commit ]
  - id: terraform-validate
    name: Validates all Terraform configuration files with TF validate
    entry: cd terraform && make validate
    language: system
    stages: [ commit ]
<% } -%>
<% if (includeDvc) { -%>
  - id: dvc-pre-push
    name: DVC pre-push
    entry: dvc
    args:
      - git-hook
      - pre-push
    require_serial: true
    verbose: true
    language: system
    stages: [push]
<% } -%>
